# Generated by Windows Sandbox Builder
$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$Root = 'C:\SandboxToolbox'
$Downloads = Join-Path $Root 'Downloads'
$Tools = Join-Path $Root 'Tools'

foreach ($path in @($Root, $Downloads, $Tools)) {
    New-Item -Path $path -ItemType Directory -Force | Out-Null
}

function Download-File {
    param(
        [Parameter(Mandatory)][string]$Url,
        [Parameter(Mandatory)][string]$Output
    )

    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest -Uri $Url -OutFile $Output -UseBasicParsing -ErrorAction Stop
}

function Expand-Zip {
    param(
        [Parameter(Mandatory)][string]$ZipPath,
        [Parameter(Mandatory)][string]$DestinationPath
    )

    if (Test-Path $DestinationPath) {
        Remove-Item -Path $DestinationPath -Recurse -Force
    }

    New-Item -Path $DestinationPath -ItemType Directory -Force | Out-Null
    Add-Type -AssemblyName System.IO.Compression.FileSystem -ErrorAction Stop
    [System.IO.Compression.ZipFile]::ExtractToDirectory($ZipPath, $DestinationPath)
}

# The generator inserts resolved application install blocks below.
{{APPLICATION_INSTALL_BLOCKS}}

Write-Host 'Windows Sandbox Builder provisioning completed.'
