import type { AppManifest } from '../types.js';
import { generateRunner as generateRunnerV2 } from './runner-v2.js';

const psQuote = (value: string) => `'${value.replaceAll("'", "''")}'`;

function decodeUtf8Base64(value: string): string {
  const binary = atob(value);
  const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}

function encodeUtf8Base64(value: string): string {
  const bytes = new TextEncoder().encode(value);
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function retryPath(app: AppManifest): string {
  return `C:\\SandboxToolbox\\Retry\\${app.id}.ps1`;
}

function generateRetryInstallBlock(app: AppManifest): string {
  const fileName = app.install.fileName ?? `${app.id}.download`;
  const downloadPath = `C:\\SandboxToolbox\\Downloads\\${fileName}`;
  const lines: string[] = [
    `Download-File -Url ${psQuote(app.install.url)} -Output ${psQuote(downloadPath)} -Description ${psQuote(app.name)}`,
  ];

  switch (app.install.type) {
    case 'zip':
      if (!app.install.extractTo) throw new Error(`${app.id}: zip install requires extractTo`);
      lines.push(`Expand-Zip -ZipPath ${psQuote(downloadPath)} -DestinationPath ${psQuote(app.install.extractTo)}`);
      break;
    case 'portable':
      if (!app.install.extractTo) throw new Error(`${app.id}: portable install requires extractTo`);
      lines.push(`New-Item -Path ${psQuote(app.install.extractTo)} -ItemType Directory -Force | Out-Null`);
      lines.push(`Copy-Item -Path ${psQuote(downloadPath)} -Destination (Join-Path ${psQuote(app.install.extractTo)} ${psQuote(fileName)}) -Force`);
      break;
    case 'exe':
      lines.push(`$p = Start-Process -FilePath ${psQuote(downloadPath)} -ArgumentList ${psQuote(app.install.silentArgs ?? '')} -Wait -PassThru`);
      lines.push(`if ($p.ExitCode -notin @(0,3010)) { throw ${psQuote(`${app.name} installer failed`)} + " with exit code $($p.ExitCode)." }`);
      break;
    case 'msi':
      lines.push(`$p = Start-Process -FilePath 'msiexec.exe' -ArgumentList @('/i', ${psQuote(downloadPath)}, ${psQuote(app.install.silentArgs ?? '/qn /norestart')}) -Wait -PassThru`);
      lines.push(`if ($p.ExitCode -notin @(0,3010)) { throw ${psQuote(`${app.name} installer failed`)} + " with exit code $($p.ExitCode)." }`);
      break;
    case 'script':
      lines.push(`& powershell.exe -NoProfile -ExecutionPolicy Bypass -File ${psQuote(downloadPath)}`);
      lines.push(`if ($LASTEXITCODE -and $LASTEXITCODE -ne 0) { throw ${psQuote(`${app.name} script failed`)} }`);
      break;
  }

  if (app.install.postInstall?.length) lines.push(...app.install.postInstall);

  if (app.detection.type === 'file') {
    lines.push(`if (-not (Test-Path -LiteralPath ${psQuote(app.detection.value)})) { throw ${psQuote(`${app.name} was not detected after provisioning.`)} }`);
  } else if (app.detection.type === 'registry') {
    lines.push(`if (-not (Test-Path -LiteralPath ${psQuote(app.detection.value)})) { throw ${psQuote(`${app.name} registry detection failed after provisioning.`)} }`);
  } else {
    lines.push(`& powershell.exe -NoProfile -Command ${psQuote(app.detection.value)} | Out-Null; if ($LASTEXITCODE -ne 0) { throw ${psQuote(`${app.name} command detection failed after provisioning.`)} }`);
  }

  return lines.join('\n');
}

function generateRetryScript(app: AppManifest): string {
  const installBlock = generateRetryInstallBlock(app);
  return `# Generated by Build My Sandbox - retry ${app.name}
$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$Root = 'C:\\SandboxToolbox'
$Downloads = Join-Path $Root 'Downloads'
$Logs = Join-Path $Root 'Logs'
$StateFile = Join-Path $Logs 'ProvisioningState.log'
$LogFile = Join-Path $Logs 'BuildMySandbox.log'
function Write-Log { param([string]$Message) Add-Content -Path $LogFile -Value ("[{0}] {1}" -f (Get-Date -Format 'HH:mm:ss'), $Message) -Encoding UTF8 }
function Write-StepState { param([string]$Name,[string]$Status,[string]$Message='') $safeMessage = ($Message -replace '[\\r\\n|]+',' '); Add-Content -Path $StateFile -Value "$Name|$Status|$safeMessage" -Encoding UTF8 }
function Download-File {
  param([string]$Url,[string]$Output,[string]$Description)
  Write-Log "RETRY DOWNLOAD: $Description from $Url"
  $oldProgress = $ProgressPreference; $ProgressPreference = 'SilentlyContinue'
  try { Invoke-WebRequest -Uri $Url -OutFile $Output -UseBasicParsing -ErrorAction Stop } finally { $ProgressPreference = $oldProgress }
  if (-not (Test-Path $Output) -or (Get-Item $Output).Length -le 0) { throw 'Downloaded file is empty.' }
}
function Expand-Zip {
  param([string]$ZipPath,[string]$DestinationPath)
  if (Test-Path $DestinationPath) { Remove-Item $DestinationPath -Recurse -Force }
  New-Item $DestinationPath -ItemType Directory -Force | Out-Null
  Add-Type -AssemblyName System.IO.Compression.FileSystem -ErrorAction Stop
  [System.IO.Compression.ZipFile]::ExtractToDirectory($ZipPath,$DestinationPath)
}
$name = ${psQuote(app.name)}
Write-StepState -Name $name -Status 'INSTALLING'
Write-Log "RETRY START: $name"
try {
${installBlock}
  Write-StepState -Name $name -Status 'READY'
  Write-Log "RETRY READY: $name"
} catch {
  $message = $_.Exception.Message
  Write-StepState -Name $name -Status 'FAILED' -Message $message
  Write-Log "RETRY FAILED: $name - $message"
}
`;
}

function patchProvisioningUi(ui: string, apps: AppManifest[]): string {
  const retryEntries = apps
    .map((app) => `  ${psQuote(app.name)} = ${psQuote(retryPath(app))}`)
    .join('\n');

  ui = ui.replace(
    '$Rows = @{}',
    `$Rows = @{}\n$RetryButtons = @{}\n$RetryMap = @{\n${retryEntries}\n}`,
  );

  ui = ui.replace(
    "$Rows[$name] = [pscustomobject]@{ Dot = $dot; Badge = $badge; Text = $badgeText; Actions = $actionPanel; HasActions = ($actions.Count -gt 0) }",
    "$Rows[$name] = [pscustomobject]@{ Dot = $dot; Badge = $badge; Text = $badgeText; Actions = $actionPanel; HasActions = ($actions.Count -gt 0); Card = $card }",
  );

  ui = ui.replace(
    "$Rows[$name] = [pscustomobject]@{ Dot = $dot; Badge = $badge; Text = $badgeText; Actions = $actionButton; HasActions = ($actions.Count -gt 0) }",
    "$Rows[$name] = [pscustomobject]@{ Dot = $dot; Badge = $badge; Text = $badgeText; Actions = $actionButton; HasActions = ($actions.Count -gt 0); Card = $card }",
  );

  // Convert the JSON object to a real hashtable. Display names such as Notepad++
  // are then plain string keys and no longer depend on PowerShell property syntax.
  ui = ui.replace(
    String.raw`$ActionMap = ConvertFrom-Json $ActionJson`,
    String.raw`$ActionObject = ConvertFrom-Json $ActionJson
$ActionMap = @{}
foreach ($actionProperty in $ActionObject.PSObject.Properties) {
  $ActionMap[[string]$actionProperty.Name] = @($actionProperty.Value)
}`,
  );

  ui = ui.replace(
    String.raw`  [System.Windows.Controls.Grid]::SetColumn($actionPanel, 2)
  $grid.Children.Add($actionPanel) | Out-Null`,
    String.raw`  [System.Windows.Controls.Grid]::SetColumn($actionPanel, 2)
  $grid.Children.Add($actionPanel) | Out-Null

  $retryButton = New-Object System.Windows.Controls.Button
  $retryButton.Content = 'Retry'
  $retryButton.Visibility = 'Collapsed'
  $retryButton.Margin = '10,0,14,0'
  $retryButton.Padding = '12,6'
  $retryButton.MinHeight = 30
  $retryButton.Background = '#FFF6F2'
  $retryButton.Foreground = '#B55F4F'
  $retryButton.BorderBrush = '#F0CDC4'
  $retryButton.BorderThickness = 1
  $retryButton.FontSize = 12
  $retryButton.FontWeight = 'SemiBold'
  $retryButton.Cursor = 'Hand'
  $retryButton.VerticalAlignment = 'Center'
  [System.Windows.Controls.Grid]::SetColumn($retryButton, 2)
  $grid.Children.Add($retryButton) | Out-Null
  $RetryButtons[[string]$name] = $retryButton

  if ($RetryMap.ContainsKey([string]$name)) {
    $capturedRetryPath = [string]$RetryMap[[string]$name]
    $capturedRetryName = [string]$name
    $capturedRetryButton = $retryButton
    $retryButton.Add_Click(({
      try {
        if (-not (Test-Path -LiteralPath $capturedRetryPath)) { throw "Retry script for $capturedRetryName was not found." }
        $capturedRetryButton.IsEnabled = $false
        Start-Process -FilePath 'powershell.exe' -ArgumentList @('-NoLogo','-NoProfile','-WindowStyle','Hidden','-ExecutionPolicy','Bypass','-File',$capturedRetryPath) -WindowStyle Hidden | Out-Null
      } catch {
        $capturedRetryButton.IsEnabled = $true
        [System.Windows.MessageBox]::Show($_.Exception.Message, 'Build My Sandbox') | Out-Null
      }
    }).GetNewClosure())
  }`,
  );

  // Force the filtered result back into an array. Windows PowerShell unwraps a
  // single pipeline result to a scalar; without @(...), HasActions can become
  // false for tools that have exactly one action while multi-action tools work.
  ui = ui.replace(
    String.raw`  $actions = @()
  $property = $ActionMap.PSObject.Properties[$name]
  if ($property) { $actions = @($property.Value) | Where-Object { $_.ui -ne $false } }`,
    String.raw`  $actions = @()
  if ($ActionMap.ContainsKey([string]$name)) {
    $actions = @($ActionMap[[string]$name] | Where-Object { $_.ui -ne $false })
  }`,
  );

  // ProvisioningState.log uses Name|Status|Message. Match the original two-field
  // parser without depending on the exact number of escaped backslashes emitted
  // by the TypeScript template string.
  ui = ui.replace(
    /      \$parts = \$line -split '[^']+', 2\n      if \(\$parts\.Count -eq 2\) \{ \$latest\[\$parts\[0\]\] = \$parts\[1\] \}/,
    String.raw`      $parts = $line -split '\|', 3
      if ($parts.Count -ge 2) {
        $latest[$parts[0]] = [pscustomobject]@{
          Status = $parts[1]
          Message = if ($parts.Count -ge 3) { $parts[2] } else { '' }
        }
      }`,
  );

  ui = ui.replace(
    "$state = if ($latest.ContainsKey($name)) { $latest[$name] } else { 'PENDING' }",
    "$entry = if ($latest.ContainsKey($name)) { $latest[$name] } else { $null }\n    $state = if ($entry) { [string]$entry.Status } else { 'PENDING' }",
  );

  ui = ui.replace(
    "$row.Dot.Fill = '#FF8A7A'; $row.Badge.Background = '#FFF0ED'; $row.Text.Foreground = '#C85A4D'; $row.Text.Text = 'FAILED'; $row.Actions.Visibility = 'Collapsed'",
    "$row.Dot.Fill = '#FF8A7A'; $row.Badge.Background = '#FFF0ED'; $row.Text.Foreground = '#C85A4D'; $row.Text.Text = 'FAILED'; $row.Actions.Visibility = 'Collapsed'; $row.Card.ToolTip = if ($entry -and $entry.Message) { $entry.Message } else { 'Open the log for details.' }",
  );

  ui = ui.replace(
    "$row.Dot.Fill = '#C9C5BD'; $row.Badge.Background = '#F3F0EA'; $row.Text.Foreground = '#8C8790'; $row.Text.Text = 'PENDING'; $row.Actions.Visibility = 'Collapsed'",
    "$row.Dot.Fill = '#C9C5BD'; $row.Badge.Background = '#F3F0EA'; $row.Text.Foreground = '#8C8790'; $row.Text.Text = 'PENDING'; $row.Actions.Visibility = 'Collapsed'\n    }\n\n    $retryButton = if ($RetryButtons.ContainsKey([string]$name)) { $RetryButtons[[string]$name] } else { $null }\n    if ($retryButton) {\n      if ($state -eq 'FAILED' -and $RetryMap.ContainsKey([string]$name)) {\n        $retryButton.Visibility = 'Visible'\n        $retryButton.IsEnabled = $true\n      } else {\n        $retryButton.Visibility = 'Collapsed'\n      }\n    }\n    if ($false) {",
  );

  ui = ui.replace(
    "if ($latest['__ALL__'] -eq 'READY') {",
    "if ($latest.ContainsKey('__ALL__') -and $latest['__ALL__'].Status -eq 'READY') {",
  );

  ui = ui.replace(
    "} elseif ($latest['__ALL__'] -eq 'FAILED') {\n    $title.Text = 'Your sandbox is ready with a few bumps.'\n    $subtitle.Text = 'One or more steps failed. Open the log for details.'",
    "} elseif ($latest.ContainsKey('__ALL__') -and $latest['__ALL__'].Status -eq 'FAILED') {\n    $title.Text = 'Your sandbox is ready with a few bumps.'\n    $firstFailure = $Names | ForEach-Object { if ($latest.ContainsKey($_) -and $latest[$_].Status -eq 'FAILED') { [pscustomobject]@{ Name = $_; Message = $latest[$_].Message } } } | Select-Object -First 1\n    $subtitle.Text = if ($firstFailure -and $firstFailure.Message) { \"$($firstFailure.Name): $($firstFailure.Message)\" } else { 'One or more steps failed. Open the log for details.' }",
  );

  // __ALL__ reflects the initial run. Recalculate the header from current row
  // states so a successful retry can move the Toolbox back to the ready state.
  ui = ui.replace(
    "  }\n}\n\nRefresh-State",
    String.raw`  }

  $failedNames = @($Names | Where-Object { $latest.ContainsKey($_) -and $latest[$_].Status -eq 'FAILED' })
  if ($ready -eq $Names.Count) {
    $title.Text = 'Your sandbox is ready!'
    $subtitle.Text = 'Everything finished successfully. Time to play.'
  } elseif ($failedNames.Count -gt 0) {
    $title.Text = 'Your sandbox is ready with a few bumps.'
    $firstFailure = $failedNames | ForEach-Object { [pscustomobject]@{ Name = $_; Message = $latest[$_].Message } } | Select-Object -First 1
    $subtitle.Text = if ($firstFailure -and $firstFailure.Message) { "$($firstFailure.Name): $($firstFailure.Message)" } else { 'One or more steps failed. Retry the failed tool or open the Toolbox folder for details.' }
  } else {
    $title.Text = 'Building your sandbox...'
    $subtitle.Text = 'A little sand, a few tools, almost ready.'
  }
}

Refresh-State`,
  );

  ui = ui.replace(
    String.raw`$window = New-Object System.Windows.Window
$window.Title = 'Build My Sandbox'`,
    String.raw`try {
  Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;
public static class BmsTaskbarIdentity {
  [DllImport("shell32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
  public static extern int SetCurrentProcessExplicitAppUserModelID(string appID);
}
'@ -ErrorAction SilentlyContinue
  [BmsTaskbarIdentity]::SetCurrentProcessExplicitAppUserModelID('BuildMySandbox.Toolbox') | Out-Null
} catch {}

$IconPath = 'C:\SandboxToolbox\BuildMySandbox.ico'
$window = New-Object System.Windows.Window
if (Test-Path $IconPath) {
  try {
    $window.Icon = [System.Windows.Media.Imaging.BitmapFrame]::Create([System.Uri]::new($IconPath))
  } catch {}
}
$window.Title = 'Build My Sandbox'`,
  );

  ui = ui.replace("$mark.Background = '#6F7FF6'", "$mark.Background = 'Transparent'");

  ui = ui.replace(
    '$mark.Child = $markText',
    String.raw`if ($window.Icon) {
  $markImage = New-Object System.Windows.Controls.Image
  $markImage.Source = $window.Icon
  $markImage.Width = 56
  $markImage.Height = 56
  $markImage.Stretch = 'Uniform'
  $mark.Child = $markImage
} else {
  $mark.Child = $markText
}`,
  );

  ui = ui.replace(
    String.raw`    $actionButton.Margin = '0,0,6,0'
    $actionButton.Padding = '10,5'
    $actionButton.Background = '#EEF3FF'
    $actionButton.Foreground = '#5265C9'
    $actionButton.BorderBrush = '#D9D9FF'`,
    String.raw`    $actionButton.Margin = '0,0,7,0'
    $actionButton.Padding = '12,6'
    $actionButton.MinHeight = 30
    $actionButton.Background = '#F5F3FF'
    $actionButton.Foreground = '#5753C8'
    $actionButton.BorderBrush = '#D6D0FF'
    $actionButton.BorderThickness = 1
    $actionButton.FontSize = 12
    $actionButton.FontWeight = 'SemiBold'
    $actionButton.Cursor = 'Hand'`,
  );

  ui = ui.replace(
    "$badge.Background = '#F3F0EA'",
    "$badge.Background = '#F3F0EA'\n  $badge.VerticalAlignment = 'Center'",
  );

  ui = ui.replace(
    "$badgeText.Foreground = '#8C8790'",
    "$badgeText.Foreground = '#8C8790'\n  $badgeText.HorizontalAlignment = 'Center'\n  $badgeText.VerticalAlignment = 'Center'\n  $badgeText.TextAlignment = 'Center'",
  );

  ui = ui.replace(
    String.raw`$toolboxButton = New-Object System.Windows.Controls.Button
$toolboxButton.Content = 'Open Toolbox'
$toolboxButton.Padding = '12,6'
$toolboxButton.Margin = '0,0,8,0'
$toolboxButton.Add_Click({ Start-Process explorer.exe -ArgumentList 'C:\SandboxToolbox' | Out-Null })
$footer.Children.Add($toolboxButton) | Out-Null
$logButton = New-Object System.Windows.Controls.Button
$logButton.Content = 'Open log'
$logButton.Padding = '12,6'
$logButton.Add_Click({ if (Test-Path $LogFile) { Start-Process notepad.exe -ArgumentList $LogFile | Out-Null } })
$footer.Children.Add($logButton) | Out-Null`,
    String.raw`$toolboxButton = New-Object System.Windows.Controls.Button
$toolboxButton.Content = 'Open Toolbox Folder'
$toolboxButton.Padding = '14,7'
$toolboxButton.Background = '#F5F3FF'
$toolboxButton.Foreground = '#5753C8'
$toolboxButton.BorderBrush = '#D6D0FF'
$toolboxButton.BorderThickness = 1
$toolboxButton.FontSize = 12
$toolboxButton.FontWeight = 'SemiBold'
$toolboxButton.Cursor = 'Hand'
$toolboxButton.Add_Click({ Start-Process explorer.exe -ArgumentList 'C:\SandboxToolbox' | Out-Null })
$footer.Children.Add($toolboxButton) | Out-Null`,
  );

  return ui;
}

export function generateRunner(apps: AppManifest[]): string {
  let runner = generateRunnerV2(apps);

  // Tool actions belong in the Toolbox UI only. Strip every generated per-tool
  // launcher and Start menu shortcut. The single BMS Toolbox shortcut is added
  // after this cleanup step.
  runner = runner.replace(/^.*C:\\SandboxToolbox\\Launchers\\.*\r?\n?/gm, '');
  runner = runner.replace(/^New-Shortcut -Path 'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Build My Sandbox\\[^']+\.lnk'.*\r?\n?/gm, '');

  runner = runner.replace(
    "$Launchers = Join-Path $Root 'Launchers'",
    "$Launchers = Join-Path $Root 'Launchers'\n$Retry = Join-Path $Root 'Retry'",
  );
  runner = runner.replace(
    "foreach ($path in @($Root,$Downloads,$Tools,$Logs,$Launchers,$StartMenu))",
    "foreach ($path in @($Root,$Downloads,$Tools,$Logs,$Launchers,$Retry,$StartMenu))",
  );

  runner = runner.replace(
    "function Write-StepState { param([string]$Name,[string]$Status) Add-Content -Path $StateFile -Value \"$Name|$Status\" -Encoding UTF8 }",
    "function Write-StepState { param([string]$Name,[string]$Status,[string]$Message='') $safeMessage = ($Message -replace '[\\r\\n|]+',' '); Add-Content -Path $StateFile -Value \"$Name|$Status|$safeMessage\" -Encoding UTF8 }",
  );

  runner = runner.replace(
    "catch { $script:Failures += \"$($Name): $($_.Exception.Message)\"; Write-StepState -Name $Name -Status 'FAILED'; Write-Log \"FAILED: $($Name) - $($_.Exception.Message)\" }",
    "catch { $message = $_.Exception.Message; $script:Failures += \"$($Name): $message\"; Write-StepState -Name $Name -Status 'FAILED' -Message $message; Write-Log \"FAILED: $($Name) - $message\" }",
  );

  runner = runner.replace(
    String.raw`function New-Shortcut {
  param([string]$Path,[string]$Target,[string]$Arguments='',[string]$WorkingDirectory='')
  $shell = New-Object -ComObject WScript.Shell
  $shortcut = $shell.CreateShortcut($Path)
  $shortcut.TargetPath = $Target
  $shortcut.Arguments = $Arguments
  if ($WorkingDirectory) { $shortcut.WorkingDirectory = $WorkingDirectory }
  $shortcut.Save()
}`,
    String.raw`function New-Shortcut {
  param([string]$Path,[string]$Target,[string]$Arguments='',[string]$WorkingDirectory='',[string]$IconLocation='')
  $shell = New-Object -ComObject WScript.Shell
  $shortcut = $shell.CreateShortcut($Path)
  $shortcut.TargetPath = $Target
  $shortcut.Arguments = $Arguments
  if ($WorkingDirectory) { $shortcut.WorkingDirectory = $WorkingDirectory }
  if ($IconLocation) { $shortcut.IconLocation = $IconLocation }
  $shortcut.Save()
}`,
  );

  runner = runner.replace(
    "New-Shortcut -Path (Join-Path $Desktop 'Build My Sandbox.lnk') -Target 'explorer.exe' -Arguments $Root -WorkingDirectory $Root",
    String.raw`$IconPath = Join-Path $Root 'BuildMySandbox.ico'
try {
  Invoke-WebRequest -Uri 'https://buildmysandbox.com/favicon.ico' -OutFile $IconPath -UseBasicParsing -ErrorAction Stop
} catch {
  Write-Log "WARNING: Build My Sandbox icon could not be downloaded: $($_.Exception.Message)"
}
$toolboxArgs = "-NoLogo -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File $UiScript"
$iconRef = "$IconPath,0"
New-Shortcut -Path (Join-Path $Desktop 'Build My Sandbox Toolbox.lnk') -Target 'powershell.exe' -Arguments $toolboxArgs -WorkingDirectory $Root -IconLocation $iconRef
New-Shortcut -Path (Join-Path $StartMenu 'Build My Sandbox Toolbox.lnk') -Target 'powershell.exe' -Arguments $toolboxArgs -WorkingDirectory $Root -IconLocation $iconRef`,
  );

  const retryWrites = apps
    .map((app) => {
      const path = retryPath(app);
      const base64 = encodeUtf8Base64(generateRetryScript(app));
      return `[IO.File]::WriteAllBytes(${psQuote(path)}, [Convert]::FromBase64String('${base64}'))`;
    })
    .join('\n');

  if (retryWrites) {
    runner = runner.replace(
      "Start-Process -FilePath 'powershell.exe' -ArgumentList @('-NoLogo','-NoProfile','-WindowStyle','Hidden','-ExecutionPolicy','Bypass','-File',$UiScript) -WindowStyle Hidden",
      `${retryWrites}\nStart-Process -FilePath 'powershell.exe' -ArgumentList @('-NoLogo','-NoProfile','-WindowStyle','Hidden','-ExecutionPolicy','Bypass','-File',$UiScript) -WindowStyle Hidden`,
    );
  }

  const uiMatch = runner.match(/\[IO\.File\]::WriteAllBytes\(\$UiScript, \[Convert\]::FromBase64String\('([^']+)'\)\)/);
  if (uiMatch?.[1]) {
    const patchedUi = patchProvisioningUi(decodeUtf8Base64(uiMatch[1]), apps);
    const patchedBase64 = encodeUtf8Base64(patchedUi);
    runner = runner.replace(uiMatch[1], patchedBase64);
  }

  return runner;
}