import type { AppManifest } from '../types.js';

const psQuote = (value: string) => `'${value.replaceAll("'", "''")}'`;

export function generateInstallBlock(app: AppManifest): string {
  const fileName = app.install.fileName ?? `${app.id}.download`;
  const downloadPath = `C:\\SandboxToolbox\\Downloads\\${fileName}`;

  const lines: string[] = [
    `Write-Host ${psQuote(`Installing ${app.name}...`)}`,
    `Download-File -Url ${psQuote(app.install.url)} -Output ${psQuote(downloadPath)}`,
  ];

  switch (app.install.type) {
    case 'zip':
      if (!app.install.extractTo) throw new Error(`${app.id}: zip install requires extractTo`);
      lines.push(`Expand-Zip -ZipPath ${psQuote(downloadPath)} -DestinationPath ${psQuote(app.install.extractTo)}`);
      break;
    case 'portable':
      if (!app.install.extractTo) throw new Error(`${app.id}: portable install requires extractTo`);
      lines.push(`New-Item -Path ${psQuote(app.install.extractTo)} -ItemType Directory -Force | Out-Null`);
      lines.push(`Copy-Item -Path ${psQuote(downloadPath)} -Destination (Join-Path ${psQuote(app.install.extractTo)} ${psQuote(fileName)}) -Force`);
      break;
    case 'exe':
      lines.push(`$p = Start-Process -FilePath ${psQuote(downloadPath)} -ArgumentList ${psQuote(app.install.silentArgs ?? '')} -Wait -PassThru`);
      lines.push(`if ($p.ExitCode -ne 0) { throw ${psQuote(`${app.name} installer failed`)} }`);
      break;
    case 'msi':
      lines.push(`$p = Start-Process -FilePath 'msiexec.exe' -ArgumentList @('/i', ${psQuote(downloadPath)}, ${psQuote(app.install.silentArgs ?? '/qn /norestart')}) -Wait -PassThru`);
      lines.push(`if ($p.ExitCode -notin @(0,3010)) { throw ${psQuote(`${app.name} installer failed`)} }`);
      break;
    case 'script':
      lines.push(`& powershell.exe -NoProfile -ExecutionPolicy Bypass -File ${psQuote(downloadPath)}`);
      break;
  }

  return lines.join('\n');
}

export function generateRunner(apps: AppManifest[]): string {
  const blocks = apps.map(generateInstallBlock).join('\n\n');
  return `# Generated by Windows Sandbox Builder\n$ErrorActionPreference = 'Stop'\n[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12\n\n$Root = 'C:\\SandboxToolbox'\n$Downloads = Join-Path $Root 'Downloads'\n$Tools = Join-Path $Root 'Tools'\nforeach ($path in @($Root,$Downloads,$Tools)) { New-Item -Path $path -ItemType Directory -Force | Out-Null }\n\nfunction Download-File { param([string]$Url,[string]$Output) $ProgressPreference='SilentlyContinue'; Invoke-WebRequest -Uri $Url -OutFile $Output -UseBasicParsing -ErrorAction Stop }\nfunction Expand-Zip { param([string]$ZipPath,[string]$DestinationPath) if(Test-Path $DestinationPath){Remove-Item $DestinationPath -Recurse -Force}; New-Item $DestinationPath -ItemType Directory -Force | Out-Null; Add-Type -AssemblyName System.IO.Compression.FileSystem -ErrorAction Stop; [System.IO.Compression.ZipFile]::ExtractToDirectory($ZipPath,$DestinationPath) }\n\n${blocks}\n\nWrite-Host 'Windows Sandbox Builder provisioning completed.'\n`;
}
